### ISSUE TITLE
Install-Media folders on /Volumes

### ISSUE THREAD

**Issue by peekpt** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#172]
This a tricky one.
On error, sometimes the script leaves on /Volumes "Install-media" empty folders causing subsequent installs to fail.

I accidentally created an apfs volume instead of Journaling one and createinstallmedia prompts me right away that the installation could not continue because of wrong disk format.

It happens that this situation leaved an empty install-media folder in /Volumes

On next try your script was trying to write in the same volume "Install-Media" instead of "Install-Media 2" and I get the error again. 
There's no possible way to make it work unless you manually delete the folders.

Possible fix, create something to unmount and delete all Install-media folders before

**Comment by chris1111** [comment]
286 / 5 000
Résultats de traduction
Résultat de traduction
It's been working like this for 6 years and no one including me complains about anything

Use the program the right way
you open issues for things that don't really exist because since the ventura support everything works perfectly confirmed by several testers
