### ISSUE TITLE
Support for HP Elitebook 2560p sandy bridge.

### ISSUE THREAD

**Issue by neodavids** [chris1111/HP-Probook-EliteBook-Package-Creator-OC#4]
Can this work for Intel HD 3000 elitebook 2560p core i5 sandy bridge?
Working smbios is MacBook Pro 8,1.

**Comment by chris1111** [comment]
No support Sandy bridge for Big Sur 
 Try to use this https://github.com/chris1111/HP-Probook-EliteBook-Package-Creator with High Sierra native support Intel HD 300 otherwise if you try Moja or Cat you need the patch https://github.com/chris1111/Legacy-Video-patch https://github.com/chris1111/Fix-Graphics-HD-3000-Mojave-10.14

**Comment by neodavids** [comment]
Okay, I would have love to switch to opencore for booting Mojave..
I also want to add that following your guide for post install gives me wierd red screen color I had to switch to from MacBook Pro 9,2 to 8,1 to get normal color... Brightness control not working ...
